
server:
  port: 8080

#neo4j 数据库配置
spring:
  data:
    neo4j:
      #uri: bolt://47.100.226.85:7687
      uri: http://47.100.226.85:7474
      username: neo4j
      password: neo4j123
  mvc:
    static-path-pattern: /**
  # 设置静态资源访问路径
  resources:
    static-locations: classpath:/static/,/images/,file:${upload.path}}
  jpa:
    show-sql: true

# 设置本地文件保存路径
upload:
  path: /home/zqq/friends/
  #path: C:/Users/17469/Desktop/images/

visit:
  path: http://47.100.226.85/friends/
  #path: http://192.168.1.101:8080/uploaded/